In [ ]:
# exploratory test
# random package to create random indexes
# and it includes sample module, which has range() and len() function embaded
import pandas as pd
digits = pd.read_csv("http://archive.ics.uci.edu/ml/machine-learning-datasets/optdigits/optdigits.tra", header = None)
# using describe(), head(), tail(), sample() to get some real records from the dataset
from random import sample
randomIndex = np.array(sample(range(len(digits)), 5))
digitsSample = digits.ix[randomIndex]
print(digitsSample)
# queries the data
iris.query('Petal_length > Sepal_length')
iris.query('Petal_length == Sepal_length')
# same as 
iris[iris.Petal_length > iris.Sepal_length]

# to identify missing values
pd.isnull()
# how to handle missing values
mean = np.mean(df.Salary)
df. = df.Salry.fillna(mean)
# how to drop labels with missing values
df.dropna(axis = 0) # asix = 0 refers to rows
df.dropna(axis = 1) # axis = 1 refers to columns



In [1]:
from sklearn.model_selection import train_test_split

In [ ]:
# how to examine data
data.describe()
data.head(5)
data.tail(5)

# how to convert data type into the correct format
# to be filled

# for large data set, take a sample of the data
data.sample(10)
# another way to perform sampling is to create random index
# and then get random rows in the dataframe
print(data.info())

In [5]:
import numpy as np
a = np.arange(9).reshape((3,3))
print(a)
print(np.max(a)) # 全局最大
print(np.max(a, axis = 0)) # 每列最大 
print(np.max(a, axis = 1)) # 每行最大 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
8
[6 7 8]
[2 5 8]


In [4]:
>>> print(np.where(a==np.max(a)))
(array([2], dtype=int64), array([2], dtype=int64))
>>> print(np.where(a==np.max(a,axis=0)))
(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
print(np.where(a==np.max(a)))


(array([2]), array([2]))


In [7]:
print(np.where(a==np.max(a,axis=0)))

(array([2, 2, 2]), array([0, 1, 2]))
